#cloud-config
package_update: true
packages:
  - nodejs
  - npm
  - git
runcmd:
  - mkdir -p /home/cloud/frontend
  - git clone https://github.com/CallmeVRM/azure-LB02 /tmp/lab
  - cp /tmp/lab/frontend/frontend2.js /home/cloud/frontend/server.js
  - cp /tmp/lab/frontend/index2.html /home/cloud/frontend/index2.html
  - chown -R cloud:cloud /home/cloud/frontend
  - cd /home/cloud/frontend
  - npm init -y
  - npm install express
  - |
    cat > /etc/systemd/system/frontend2.service << 'SERVICEOF'
    [Unit]
    Description=Frontend-2 Node.js Server (Port 8443)
    After=network.target
    
    [Service]
    Type=simple
    User=cloud
    WorkingDirectory=/home/cloud/frontend
    ExecStart=/usr/bin/node /home/cloud/frontend/server.js
    Restart=always
    RestartSec=5
    StandardOutput=journal
    StandardError=journal
    
    [Install]
    WantedBy=multi-user.target
    SERVICEOF
  - systemctl daemon-reload
  - systemctl enable frontend2
  - systemctl start frontend2
  - echo "Frontend-2 service created and started on port 8443"