#cloud-config
package_update: true
packages:
  - nodejs
  - npm
  - git
runcmd:
  - mkdir -p /home/cloud/frontend
  - git clone https://github.com/CallmeVRM/azure-LB02 /tmp/lab
  - cp /tmp/lab/frontend/frontend2_b.js /home/cloud/frontend/server.js
  - cp /tmp/lab/frontend/index2_b.html /home/cloud/frontend/index2_b.html
  - chown -R cloud:cloud /home/cloud/frontend
  - cd /home/cloud/frontend
  - npm init -y
  - npm install express
  - node /home/cloud/frontend/server.js &
  - echo "Frontend-2_b server is running on port 8443"