#cloud-config
package_update: true
packages:
  - nodejs
  - npm
  - git
runcmd:
  - mkdir -p /home/cloud/frontend
  - git clone https://github.com/CallmeVRM/azure-LB02 /tmp/lab
  - cp /tmp/lab/frontend/frontend1.js /home/cloud/frontend/server.js
  - cp /tmp/lab/frontend/index1.html /home/cloud/frontend/index1.html
  - chown -R cloud:cloud /home/cloud/frontend
  - cd /home/cloud/frontend
  - npm init -y
  - npm install express
  - |
    cat > /etc/systemd/system/frontend1.service << 'SERVICEOF'
    [Unit]
    Description=Frontend-1 server.js Server (Port 80)
    After=network.target
    
    [Service]
    Type=simple
    User=cloud
    WorkingDirectory=/home/cloud/frontend
    ExecStart=/usr/bin/node /home/cloud/frontend/server.js
    Restart=always
    RestartSec=5
    StandardOutput=journal
    StandardError=journal
    AmbientCapabilities=CAP_NET_BIND_SERVICE
    
    [Install]
    WantedBy=multi-user.target
    SERVICEOF
  - systemctl daemon-reload
  - systemctl enable frontend1
  - systemctl start frontend1
  - echo "Frontend-1 service created and started on port 80"